/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_serce_nativelib_NativeLib */

#ifndef _Included_me_serce_nativelib_NativeLib
#define _Included_me_serce_nativelib_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_serce_nativelib_NativeLib
 * Method:    goodNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_me_serce_nativelib_NativeLib_goodNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     me_serce_nativelib_NativeLib
 * Method:    badNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_me_serce_nativelib_NativeLib_badNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
